# Generated by Django 3.1.4 on 2020-12-24 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='箱番号')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Ndl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='タイトル')),
                ('creator', models.CharField(blank=True, max_length=255, null=True, verbose_name='著者')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='出版社')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='巻数')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='タイトル')),
                ('creator', models.CharField(blank=True, max_length=255, null=True, verbose_name='著者')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='出版社')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.box')),
                ('ndl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ndl')),
            ],
        ),
    ]
